@startuml

package Edge{

component "ESP32"

component "Water Meter"

}

package Cloud{

component "Flask API"

database "SQLite"

component "Telegram"

component "Web HMI"

}

"Water Meter" --> ESP32

ESP32 --> "Flask API"

"Flask API" --> SQLite

SQLite --> "Web HMI"

"Flask API" --> Telegram

@enduml
